### ISSUE TITLE
Problem with Chibika topic

### ISSUE THREAD

**Issue by Funtimef01** [my-otter-self/otter_MAS_dialogues#1]
So under the Chibika topic, Monika calls the player, well, player, as shown in the attached image. Pretty sure this is supposed to be the player's name, and I'm sure it's an easy fix, but I figured I would point it out anyway
![Screenshot (152)](https://user-images.githubusercontent.com/102770504/188257188-f5690708-c107-40a6-9209-34571159b981.png)
Also an edit: Could just be me but I feel like the 'return love' should be in there too, just seeing as how she says "I love you [player]!" at the end

**Comment by my-otter-self** [comment]
thank you for pointing this out to me! i have fixed the [player] issue and will change it on next release. have a great day!
